# Generated by Django 2.2.11 on 2021-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact',
            new_name='s_contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
