# Generated by Django 2.2.11 on 2021-08-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210826_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, null=True, unique=True)),
                ('course_code', models.CharField(max_length=50, null=True, unique=True)),
                ('batch', models.CharField(max_length=10, null=True, unique=True)),
                ('faculty', models.CharField(max_length=50, null=True)),
                ('m', models.TimeField(null=True)),
                ('w', models.TimeField(null=True)),
                ('t', models.TimeField(null=True)),
                ('f', models.TimeField(null=True)),
            ],
        ),
    ]
