# Generated by Django 2.2.11 on 2021-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='tt',
            field=models.TimeField(null=True),
        ),
    ]
