# Generated by Django 2.2.11 on 2021-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_timetable_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('home', models.CharField(max_length=10, null=True)),
                ('approved', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
