# Generated by Django 2.2.11 on 2021-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_gatepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='f',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='m',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='t',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tt',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='w',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
