# Generated by Django 2.2.11 on 2021-08-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210826_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
