# Generated by Django 2.2.11 on 2021-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
