# Generated by Django 2.2.11 on 2021-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210826_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='p_mail',
            field=models.CharField(max_length=9999999999, null=True),
        ),
    ]
