# Generated by Django 2.2.11 on 2021-08-30 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210827_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('roll', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('relation', models.CharField(max_length=50, null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('ed', models.DateTimeField(default=django.utils.timezone.now)),
                ('leftd', models.DateTimeField(default=django.utils.timezone.now)),
                ('ld', models.CharField(max_length=50, null=True)),
                ('left', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
