# Generated by Django 2.2.11 on 2021-08-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enroll',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
